on:
  workflow_dispatch: # can be triggered manually
  push:
    paths:
      - "config/boards/shields/porcupine/*.*"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
